geekshop/urls.py
import document as document

from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from mainapp.views import IndexList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexList.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [path('^__debug_/', include(debug_toolbar.urls))]




    # urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from .views import OrderCreate, OrderUpdate, OrderList, OrderDelete, OrderDetail, order_forming_complete, \
    payment_result, update_price

app_name = 'orders'
urlpatterns = [

    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('payment/result/', payment_result, name='payment_result'),

    path('reform/<int:pk>/', update_price, name='update_price'),

]

users/urls.py
# from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import ListLoginView, RegisterFormView, ProfileFormView, Logout

app_name = 'users'
urlpatterns = [

    path('login/', ListLoginView.as_view(), name='login'),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activation_key>/', RegisterFormView.verify, name='verify')
]

ordersapp/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver

from baskets.models import Basket
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PAID = 'PD'
    PROCEEDED = 'PRD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачено'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдачи'),
        (CANCEL, 'отмена заказа'),

    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    update = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return  sum(list(map(lambda x: x.quantity, items)))

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return  sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_items(self):
        pass

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active =False
        self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'get_total_cost': sum(list(map(lambda x: x.get_product_cost(), items))),
            'get_total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукты', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=OrderItem)
def product_quantitiy_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.save()

@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=OrderItem)
def product_quantitiy_update_delete(sender, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - instance.get_item(int(instance.pk))
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from .models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemsForm(forms.ModelForm):

    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemsForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.all().select_related()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

ordersapp/views.py
# coding: utf-8
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from baskets.models import Basket
from geekshop.mixin import BaseClassContextMixin
from mainapp.models import Product
from ordersapp.forms import OrderItemsForm, OrderForm
from ordersapp.models import Order, OrderItem


class OrderList(ListView):
    model = Order
    form_class = OrderForm

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)


class OrderCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')

    def get_context_data(self, **kwargs):
        context = super(OrderCreate, self).get_context_data(**kwargs)
        context['title'] = 'GeekShop | Создать заказ'

        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if basket_items:
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=basket_items.count())
                formset = OrderFormSet()

                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                basket_items.delete()
            else:
                formset = OrderFormSet()

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

            if self.object.get_total_cost() == 0:
                self.object.delete()
        return super(OrderCreate, self).form_valid(form)


class OrderUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')

    def get_context_data(self, **kwargs):
        context = super(OrderUpdate, self).get_context_data(**kwargs)
        context['title'] = 'GeekShop | Обновление заказ'

        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
        context['orderitems'] = formset
        return context


    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

            if self.object.get_total_cost() == 0:
                self.object.delete()
        return super(OrderUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:list')


class OrderDetail(DetailView, BaseClassContextMixin):
    model = Order
    title = 'GeekShop | Просмотр заказа'


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SEND_TO_PROCEED
    order.save()


    return  HttpResponseRedirect(reverse('orders:list'))

def payment_result(request):
    # ik_co_id = 51237daa8f2a2d8413000000
    # ik_inv_id = 339800573
    # ik_inv_st = success
    # ik_pm_no = 1
    status = request.GET.get('ik_inv_st')
    if status == 'success':
        order_pk = request.GET.get('ik_pm_no')
        order_item = Order.objects.get(pk=order_pk)
        order_item.status = Order.PAID
        order_item.save()
    return HttpResponseRedirect(reverse('orders:list'))


def update_price(request, pk):
    if request.is_ajax():
        # product = Product.objects.get(pk=pk).select_related()
        product = Product.objects.get(pk=pk)
        if product:
            return JsonResponse({'price': product.price})

    return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/includes/inc_order_actions.html
{% if object.status == 'FM' %}
    <div class="container">
        <div class="d-flex justify-content-around">
            <button class="btn btn-warning btn-round form-control w-25 my-2 last">
                <a href="{% url 'orders:forming_complete' object.pk %}">
                    совершить покупку
                </a>
            </button>
            <button class="btn btn-warning btn-round form-control w-25 my-2 last">
                <a href="{% url 'orders:delete' object.pk %}">удалить</a>
            </button>
        </div>
    </div>
{% endif %}
<div class="container">

    {% if object.status == 'STP' %}

        <form name="payment" method="post" action="https://sci.interkassa.com/" accept-charset="UTF-8">
            <input type="hidden" name="ik_co_id" value="51237daa8f2a2d8413000000"/>
            <input type="hidden" name="ik_pm_no" value="{{ object.pk }}"/>
            <input type="hidden" name="ik_am" value="{{ object.get_total_cost }}"/>
            <input type="hidden" name="ik_cur" value="RUB"/>
            <input type="hidden" name="ik_suc_u" value="http://127.0.0.1:8000/orders/payment/result/"/>
            <input type="hidden" name="ik_suc_m" value="get">
            <input type="hidden" name="ik_desc" value="Платеж из интернет магазина вещей"/>
            <button type="submit" class="btn btn-success btn-round form-control my-2 last">
                Оплатить заказ
            </button>
        </form>
    {% endif %}






    <button class="btn btn-info btn-round form-control my-2 last">
        <a href="{% url 'orders:list' %}">
            к списку заказов
        </a>
    </button>
    <button class="btn btn-light btn-round form-control  my-2 last">
        <a href="{% url 'index' %}">на главную</a>
    </button>
</div>

ordersapp/templates/ordersapp/includes/inc_order_summary.html
{% if object %}
    <div class="h2">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>
    <hr>
    <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
    <div class="h4">обновлен: {{ object.updated|date:"Y-m-d H:i:s" }}</div>
    <div class="h4">cтатус: {{ object.get_status_display }}</div>
    <hr>
    {% with object_summary=object.get_summary %}
        <div class="h4">
            общее количество товаров: <span class="order_total_quantity">{{ object_summary.get_total_quantity }}</span>
        </div>
        <div class="h3">
            общая стоимость: <span class="order_total_cost">{{ object_summary.get_total_cost }}</span> руб
        </div>
    {% endwith %}
{% else %}
    <div class="h2">Новый заказ</div>
    <hr>
    <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
    {% if basket.0 %}
        <div class="h4">
            общее количество товаров: <span class="order_total_quantity">{{ basket.0.get_total_quantity }}</span>
        </div>
        <div class="h3">
            общая стоимость: <span class="order_total_cost">{{ basket.0.get_total_cost }}</span> руб
        </div>
    {% endif %}
{% endif %}
<hr>