baskets/urls.py
from django.urls import path

from baskets.views import BasketAdd, RemoveBasket, BasketEdit

app_name = 'baskets'
urlpatterns = [
    path('add/<int:product_id>/', BasketAdd.as_view(), name='basket'),
    path('remove/<int:pk>/', RemoveBasket.as_view(), name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', BasketEdit.as_view(), name='basket_edit')



]

geekshop/urls.py
import document as document

from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from mainapp.views import IndexList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexList.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [path('^__debug_/', include(debug_toolbar.urls))]




    # urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import ProductList, ProductDetail

app_name = 'products'

urlpatterns = [

    path('', ProductList.as_view(), name='index'),
    path('category/<int:category_id>/', ProductList.as_view(), name='category'),
    # path('category/<int:category_id>/page/<int:page>/', ProductList.as_view(),name='page_category'),
    path('page/<int:page>/', ProductList.as_view(), name='page'),
    path('detail/<int:pk>/', cache_page(3600)(ProductDetail.as_view()), name='detail'),
]

ordersapp/urls.py
from django.urls import path

from .views import OrderCreate, OrderUpdate, OrderList, OrderDelete, OrderDetail, order_forming_complete, \
    payment_result, update_price

app_name = 'orders'
urlpatterns = [

    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('payment/result/', payment_result, name='payment_result'),

    path('reform/<int:pk>/', update_price, name='update_price'),

]

users/urls.py
# from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import ListLoginView, RegisterFormView, ProfileFormView, Logout

app_name = 'users'
urlpatterns = [

    path('login/', ListLoginView.as_view(), name='login'),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activation_key>/', RegisterFormView.verify, name='verify')
]

mainapp/models.py
from django.db import models

# Create your models here.


class CategoryProduct(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)
    is_active = models.BooleanField('active', default=True)


    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256, unique=True)
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(CategoryProduct, on_delete=models.CASCADE)
    is_active = models.BooleanField('active', default=True, db_index=True)

    def __str__(self):
        return f' {self.name} | {self.category}'

mainapp/views.py
import os

from datetime import datetime

from django.shortcuts import get_object_or_404
from django.template.context_processors import request
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, ListView, DetailView

from mainapp.models import Product, CategoryProduct
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache
from django.conf import settings

date = datetime.now()

MODULE_DIR = os.path.dirname(__file__)

# Create your views here.


class IndexList(TemplateView):
    template_name = 'mainapp/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexList, self).get_context_data(**kwargs)
        context['date'] = datetime.now()
        context['title'] = 'GeekShop'
        return context






# def index(request):
#     context = {
#         'title': 'GeekShop',
#         'date': date
#     }
#     return render(request, 'mainapp/index.html', context)


class ProductList(ListView):

    template_name = 'mainapp/products.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_links_category(self):
        if settings.LOW_CACHE:
            key = 'links_category'
            link_category = cache.get(key)
            if link_category is None:
                link_category = CategoryProduct.objects.all()
                cache.set(key, link_category)
            return link_category
        else:
            return CategoryProduct.objects.all()

    def get_links_products(self):
        if settings.LOW_CACHE:
            key = 'links_products'
            link_produkt = cache.get(key)
            if link_produkt is None:
                link_produkt = Product.objects.all().select_related('category')
                cache.set(key, link_produkt)
            return link_produkt
        else:
            return Product.objects.all().select_related('category')


    def get_queryset(self, category_id=None, **kwargs):
        category_id = self.kwargs.get('category_id')
        if category_id != None:

            return Product.objects.filter(category_id=category_id)
        return Product.objects.all()

    # @cache_page(3600)
    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)
        context['date'] = datetime.now()
        context['title'] = 'Каталог'
        context['categories'] = CategoryProduct.objects.all()
        context['products'] = self.get_queryset()
        return context

    # @staticmethod
def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)

class ProductDetail(DetailView):
    model = Product
    template_name = 'mainapp/product_detail.html'
    context_object_name = 'product'

    # @cache_page(3600)
    def get_context_data(self, category_id=None, *args, **kwargs):
        context = super().get_context_data()

        context['product'] = get_product(self.kwargs.get('pk'))
        context['categories'] = CategoryProduct.objects.all()
        return context

# @cache_page(3600)
# def products(request, category_id=None, page=1):
#     products1 = Product.objects.filter(category_id=category_id) if category_id != None else Product.objects.all()
#
#     paginator = Paginator(products1, per_page=3)
#     try:
#         products_paginator = paginator.page(page)
#     except PageNotAnInteger:
#         products_paginator = paginator.page(1)
#     except EmptyPage:
#         products_paginator = paginator.page(paginator.num_pages)
#
#
#     context = {
#         'title': 'products',
#         'date': datetime.now(),
#         'categories': CategoryProduct.objects.all(),
#         'products': products_paginator
#     }
#     return render(request, 'mainapp/products.html', context)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="csrf-token" content="{{ csrf_token }}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}
    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <p style="color: darkgrey">{{ date|date:"D d M Y" }}</p>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
{#                     <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}#}
{#                            <i class="fas fa-user-circle"></i>#}
{#                        </a>#}
{#                    </li>#}

                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
                                {{ user.username|default:'Пользователь' }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'users:profile' %}">
                                        Профиль
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'orders:list' %}">
                                        Заказы
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admins:index' %}">
                            <i class="fas fa-users-cog"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i
                                class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/baskets.js' %}"></script>

<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/orders_scripts.js' %}"></script>
</body>

</html>

mainapp/templates/mainapp/index.html
{%  extends 'mainapp/base.html' %}
{% load static %}



{% block css %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/index.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'mainapp:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'products:index' %}" class="list-group-item">Все</a>
                </div>
            </div>

            <div class="col-lg-9">
                <div class="row my-5">
                    <div class="card" style="width: 20rem;">
                        <img src="/media/{{ product.image }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ product.price }} руб</li>
                            <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                        </ul>
                    </div>
                </div>

            </div>

        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'mainapp:category' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                    <a href="{% url 'mainapp:index' %}"
                       class="list-group-item">ВСЕ КАТЕГОРИИ</a>
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                {% include 'products/products_items.html' %}
{#                <div class="row">#}
{##}
{#                    {% for product in page_obj %}#}
{##}
{#                        <div class="col-lg-4 col-md-6 mb-4">#}
{#                            <div class="card h-100">#}
{#                                <a href="#">#}
{#                                    <img class="card-img-top"#}
{#                                         src="{{ product.image.url }}"#}
{#                                         alt="">#}
{#                                </a>#}
{#                                <div class="card-body">#}
{#                                    <h4 class="card-title">#}
{#                                        <a href="#">{{ product.name }}</a>#}
{#                                    </h4>#}
{#                                    <h5>{{ product.price }} руб.</h5>#}
{#                                    <p class="card-text">{{ product.description }}</p>#}
{#                                </div>#}
{#                                <div class="card-footer text-center">#}
{#                                    <a href="{% url 'baskets:basket' product.id %}" class="btn btn-outline-success">Отправить#}
{#                                        в корзину</a>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    {% endfor %}#}
{#                </div>#}

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}
                                {% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% for page in page_obj.paginator.page_range %}
                            <li class="page-item{% if page_obj.number == page %} disabled {% endif %}"><a class="page-link"
                                                     href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}
                        <li class="page-item{% if not page_obj.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}
                                {% else %} # {% endif %}">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- /.container -->
{% endblock %}

{% block footer %}
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}