admins/urls.py
from django.urls import path

from admins.views import UserListView, index, UserCreateView, UserUpdateView, UserDeleteView, CategoryListView, \
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, OrderListView, OrderUpdateView, OrderDeleteView

app_name = 'admins'
urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admins_user'),
    path('users-create/', UserCreateView.as_view(), name='admins_user_create'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admins_user_update'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='admins_user_delete'),
    path('category/', CategoryListView.as_view(), name='admins_category'),
    path('category-create/', CategoryCreateView.as_view(), name='admins_category_create'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(), name='admins_category_update'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='admins_category_delete'),
    path('product/', ProductListView.as_view(), name='admins_product'),
    path('product-create/', ProductCreateView.as_view(), name='admins_product_create'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='admins_product_update'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='admins_product_delete'),
    path('order/', OrderListView.as_view(), name='admins_order'),
    path('order-update/<int:pk>/', OrderUpdateView.as_view(), name='admins_order_update'),
    path('order-delete/<int:pk>/', OrderDeleteView.as_view(), name='admins_order_delete'),

]

geekshop/urls.py
import document as document

from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from mainapp.views import IndexList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexList.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [path('^__debug_/', include(debug_toolbar.urls))]




    # urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

users/urls.py
# from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import ListLoginView, RegisterFormView, ProfileFormView, Logout

app_name = 'users'
urlpatterns = [

    path('login/', ListLoginView.as_view(), name='login'),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activation_key>/', RegisterFormView.verify, name='verify')
]

ordersapp/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver

from baskets.models import Basket
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PAID = 'PD'
    PROCEEDED = 'PRD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачено'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдачи'),
        (CANCEL, 'отмена заказа'),

    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    update = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return  sum(list(map(lambda x: x.quantity, items)))

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return  sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_items(self):
        pass

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active =False
        self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'get_total_cost': sum(list(map(lambda x: x.get_product_cost(), items))),
            'get_total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукты', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=OrderItem)
def product_quantitiy_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.save()

@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=OrderItem)
def product_quantitiy_update_delete(sender, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - instance.get_item(int(instance.pk))
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()

admins/templates/admins/admin-category-read.html
{% extends 'admins/base.html'%}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Категории товаров</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории товаров
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            {% include 'admins/admins_category_table.html'%}

                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_category_create'%}">
                            <button class="btn btn-success">Создать категорию</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-category-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование категории | {{ categoryproduct.name }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_category_update' categoryproduct.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="form-row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                        {{ form.name }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.discount.id_for_label }}">Скидка</label>
                                        {{ form.discount }}
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="small mb-1"
                                               for="{{ form.description.id_for_label }}">Описание</label>
                                        {{ form.description }}
                                    </div>
                                </div>
                            </div>
{#                            <div class="form-row mb-2">#}
{#                                <div class="col-lg-12">#}
{#                                    <div class="custom-file">#}
{#                                        {{ form.image }}#}
{#                                        <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите#}
{#                                            изображение</label>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="form-row">#}
{#                                <div class="col-lg-6">#}
{#                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя#}
{#                                        пользователя</label>#}
{#                                    {{ form.username }}#}
{#                                </div>#}
{#                                <div class="col-lg-6">#}
{#                                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной#}
{#                                        почты</label>#}
{#                                    {{ form.email }}#}
{#                                </div>#}
{#                            </div>#}

                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                    </form>
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                              <form action="{% url 'admins:admins_category_delete' categoryproduct.id %}" method="post">
                                  {% csrf_token %}
                                  <input class="btn btn-danger btn-block" type="submit" value="{% if categoryproduct.is_active == False %} Активировать {% else %} Деактивировать {% endif %}">
                             </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-order-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">ЗАКАЗЫ</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Заказы
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <div class="admin_category_is_active">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                    <tr>
                                        <th>ID заказа</th>
                                        <th>Пользователь</th>
                                        <th>Активный</th>
                                        <th>Сумма</th>
                                        <th>Статус</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>ID заказа</th>
                                        <th>Пользователь</th>
                                        <th>Активный</th>
                                        <th>Сумма</th>
                                        <th>Статус</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    {% for order in orders %}
                                        <tr style="background-color: {% if order.is_active == False %} salmon {% else %} white {% endif %}">
                                            <td><a href="{% url 'admins:admins_order_update' order.pk %}"
                                            style="color: dodgerblue">{{ order.pk }}</a></td>
                                            <td>{{ order.user }}</td>
                                            <td class="text-center">
                                                {% if order.is_active %}
                                                    <i class="fas fa-check-circle"></i>
                                                {% else %}
                                                    <i class="fas fa-times-circle"></i>
                                                {% endif %}
                                            </td>
                                            <td>{{ order.get_total_cost }}</td>
                                            <td>{{ order.get_status_display }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                    {#                    <div class="card-footer">#}
                    {#                        <a href="{% url 'admins:admins_category_create'%}">#}
                    {#                            <button class="btn btn-success">Создать категорию</button>#}
                    {#                        </a>#}
                    {#                    </div>#}
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-order-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование заказа | {{ order.pk }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_order_update' order.pk %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {#                        <div class="form-row">#}
                        {#                            <div class="col-lg-6">#}
                        {#                                <div class="form-group">#}
                        {#                                    <label class="small mb-1" for="{{ form.id.id_for_label }}">ID заказа</label>#}
                        {#                                    {{ form.id }}#}
                        {#                                </div>#}
                        {#                            </div>#}
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="small mb-1"
                                       for="{{ form.status.id_for_label }}">Статус</label>
                                {{ form.status }}
                            </div>
                        </div>
                </div>
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <form action="{% url 'admins:admins_order_delete' order.pk %}" method="post">
                            {% csrf_token %}
                            <input class="btn btn-danger btn-block" type="submit" value="{% if order.is_active == False %} Активировать {% else %} Деактивировать {% endif %}">
                        </form>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-product-read.html
{% extends 'admins/base.html'%}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Товары</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Товары
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Категория</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Категория</th>
                                    <th>Активный</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for product in products %}
                                <tr style="background-color: {% if product.is_active == False %} salmon {% else %} white {% endif %}">
                                    <td><a href="{% url 'admins:admins_product_update' product.id %}" style="color: dodgerblue">{{ product.name }}</a></td>
                                    <td>{{ product.description }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>{{ product.category }}</td>
                                        <td class="text-center">
                                            {% if product.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}

                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_product_create'%}">
                            <button class="btn btn-success">Создать товар</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-product-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование категории | {{ product.name }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_product_update' product.id %}" method="post">
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                                {{ form.price }}
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                        изображение </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">

                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                                {{ form.quantity }}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                        <div class="form-row">
                            {#                            <div class="col-lg-6">#}
                            {#                                <div class="form-group">#}
                            <label class="small mb-1 "
                                   for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                            {#                                </div>#}
                            {#                            </div>#}
                        </div>
                        {#                        <div class="form-row">#}
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <form action="{% url 'admins:admins_product_delete' product.id %}" method="post">
                                {% csrf_token %}
                                <input class="btn btn-danger btn-block" type="submit"
                                       value="{% if product.is_active == False %} Активировать {% else %} Деактивировать {% endif %}">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin.html
{% extends 'admins/base.html'%}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="csrf-token" content="{{ csrf_token }}"/>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{title|title}}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admins:admins_user' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_category' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_product' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_order' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Заказы
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    {% block content %}

    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>

<script src="{% static 'js/datatable.js' %}"></script>

<script src="{% static 'js/ajax_admins.js' %}"></script>

</body>
</html>